version: '3'

services:
  db:
    image: 'postgres:17.4-alpine3.21'
    container_name: solarwatch_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: humbug123
      POSTGRES_DB: solarwatchapi
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - solarwatch_network
    ports:
      - 5432:5432
  app:
    build: .
#    image: solarwatch
    depends_on:
    -   db
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: humbug123
      DB_URL: jdbc:postgresql://db:5432/solarwatchapi
      SECRET_KEY: key
      EXPIRATION: 860000
    ports:
      - 8080:8080

